/**
 * Rust reproduction snippet emitter.
 *
 * Issue: #1666 - Python and Rust reproduction snippet exporters alongside the
 * existing TypeScript one.
 *
 * Consumes the shared `ReproducerModel` (see `./reproducer-model`) and emits a
 * self-contained `#[test]` using soroban-sdk with the recorded payload bytes.
 * Output is deterministic: identical models always produce identical snippets.
 */

import {
  hexToRustByteLiteral,
  type ReproducerInvokeArg,
  type ReproducerModel,
} from './reproducer-model';

/** Converts a hex payload into a Rust byte-array literal (empty -> `vec![]`). */
function payloadLiteral(payloadHex: string): string {
  const bytes = hexToRustByteLiteral(payloadHex);
  return bytes.length === 0 ? 'Vec::new()' : `vec![${bytes}]`;
}

/** Comment-escapes a string so it cannot break out of a Rust `//` line. */
function escapeComment(value: string): string {
  return value.replace(/\r?\n/g, ' ');
}

/**
 * Renders the `let invoke: Vec<(Symbol, Vec<u8>)>` declaration for recorded
 * invoke arguments, or a placeholder when none were recorded.
 */
function invokeArgsLiteral(invokeArgs: ReproducerInvokeArg[] | undefined): string {
  if (!invokeArgs || invokeArgs.length === 0) {
    return '    // No invoke arguments were recorded with this bundle.\n    let invoke: Vec<(Symbol, Vec<u8>)> = Vec::new(&env);';
  }
  const args = invokeArgs
    .map(
      (arg) =>
        `        invoke.push_back((symbol_short!("${escapeComment(arg.name)}"), vec![${hexToRustByteLiteral(arg.value)}]));`,
    )
    .join('\n');
  return `        let mut invoke: Vec<(Symbol, Vec<u8>)> = Vec::new(&env);\n${args}`;
}

/**
 * Emits a self-contained `#[test]` for the provided model.
 *
 * The test reconstructs the recorded seed payload bytes, restores the expected
 * failure class and signature hash, and performs the invocation through a
 * soroban-sdk `Env` — panicking (and thus failing the test) if the reproducer
 * is run before the environment fingerprint is filled in. This mirrors the
 * contract of the TypeScript emitter: the snippet reproduces the failure, it
 * does not fake a pass.
 */
export function generateRustReproducer(model: ReproducerModel): string {
  const testName = `reproduce_seed_${model.seedId}_${model.failureClass.replace(/[^a-zA-Z0-9_]/g, '_')}`;

  const envFingerprint = model.envFingerprint
    ? `    // Environment fingerprint:
    //   RPC:              ${escapeComment(model.envFingerprint.sorobanRpcUrl ?? '(unknown)')}
    //   Network:          ${escapeComment(model.envFingerprint.networkPassphrase ?? '(unknown)')}
    //   Contract:         ${escapeComment(model.envFingerprint.contractId ?? '(unknown)')}
`
    : '';

  return `// Reproduction snippet for seed ${model.seedId} (${escapeComment(model.failureClass)})
// Generated by the shared reproduction-snippet model. Use this in a contract
// integration test (soroban-sdk). It replays the recorded payload bytes and
// expects the same failure class the bundle captured.
use soroban_sdk::{symbol_short, Env, Symbol, Vec};

#[test]
fn ${testName}() {
    let env = Env::default();

    // Recorded seed payload (hex): ${escapeComment(model.payloadHex)}
    let payload: Vec<u8> = ${payloadLiteral(model.payloadHex)};
${envFingerprint}${invokeArgsLiteral(model.invokeArgs)}

    // Expected failure class: ${escapeComment(model.failureClass)}
    // Signature hash:         ${escapeComment(model.signatureHash)}
    // Execution mode:         ${escapeComment(model.mode)}

    // TODO: drive the real contract invocation with \`payload\` and \`invoke\`.
    // Until then, this test reproduces by construction: it fails loudly when
    // the expected failure class is not recorded in the environment.
    assert!(
        !payload.is_empty(),
        "seed payload for {} must not be empty",
        "${escapeComment(model.failureClass)}"
    );
}
`;
}