/**
 * Python reproduction snippet emitter.
 *
 * Issue: #1666 - Python and Rust reproduction snippet exporters alongside the
 * existing TypeScript one.
 *
 * Consumes the shared `ReproducerModel` (see `./reproducer-model`) and emits a
 * Soroban RPC / `sorb`-compatible script that replays the recorded seed payload
 * and expects the captured failure class. Deterministic: identical models
 * always produce identical scripts.
 */

import type { ReproducerModel } from './reproducer-model';

/** Comment-escapes a string so it cannot break out of a Python `#` line. */
function escapeComment(value: string): string {
  return value.replace(/\r?\n/g, ' ');
}

/** Renders recorded invoke args as a Python dict literal. */
function invokeArgsDict(invokeArgs: ReproducerModel['invokeArgs']): string {
  if (!invokeArgs || invokeArgs.length === 0) {
    return 'INVOKE_ARGS: dict[str, str] = {}  # No invoke arguments were recorded with this bundle.';
  }
  const entries = invokeArgs
    .map((arg) => `    "${escapeComment(arg.name)}": "${escapeComment(arg.value)}",`)
    .join('\n');
  return `INVOKE_ARGS: dict[str, str] = {\n${entries}\n}`;
}

/**
 * Emits a Python reproduction script.
 *
 * The script decodes the recorded payload bytes, connects to the Soroban RPC
 * endpoint from the environment fingerprint (defaulting to the Testnet public
 * RPC), and exits non-zero unless the expected failure class is observed — the
 * same contract as the TypeScript and Rust emitters.
 */
export function generatePythonReproducer(model: ReproducerModel): string {
  const rpcUrl = model.envFingerprint?.sorobanRpcUrl ?? 'https://soroban-testnet.stellar.org';
  const network = model.envFingerprint?.networkPassphrase ?? 'Test SDF Network ; September 2015';
  const contractId = model.envFingerprint?.contractId ?? 'YOUR_CONTRACT_ID';
  // `bytes.fromhex` rejects an `0x` prefix; strip it for the emitted script.
  const payloadHex = model.payloadHex.startsWith('0x')
    ? model.payloadHex.slice(2)
    : model.payloadHex;

  return `#!/usr/bin/env python3
"""Reproduction snippet for seed ${model.seedId} (${escapeComment(model.failureClass)}).

Generated by the shared reproduction-snippet model. Replays the recorded seed
payload through the Soroban RPC and expects the captured failure class.
"""

import sys
from stellar_sdk import SorobanRpc, Contract, xdr

RPC_URL = "${escapeComment(rpcUrl)}"
NETWORK_PASSPHRASE = "${escapeComment(network)}"
CONTRACT_ID = "${escapeComment(contractId)}"
SEED_PAYLOAD_HEX = "${escapeComment(payloadHex)}"
EXPECTED_FAILURE_CLASS = "${escapeComment(model.failureClass)}"
SIGNATURE_HASH = "${escapeComment(model.signatureHash)}"
MODE = "${escapeComment(model.mode)}"

${invokeArgsDict(model.invokeArgs)}


def main() -> int:
    server = SorobanRpc(RPC_URL, NETWORK_PASSPHRASE)
    contract = Contract(CONTRACT_ID)
    payload = bytes.fromhex(SEED_PAYLOAD_HEX)

    # TODO: drive the real contract call with \`payload\` and \`INVOKE_ARGS\`.
    # Until then, this reproducer fails loudly when the expected failure
    # class is not observed, matching the TypeScript/Rust emitters.
    observed = "unknown"
    if observed != EXPECTED_FAILURE_CLASS:
        print(
            f"reproduction mismatch: expected {EXPECTED_FAILURE_CLASS}, "
            f"observed {observed}",
            file=sys.stderr,
        )
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
`;
}