import { FuzzingRun } from './types';

/**
 * Formats bytes into a human-readable string.
 */
const formatBytes = (bytes: number): string => {
    if (bytes < 1024) return `${bytes} B`;
    if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
    return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
};

/**
 * Formats fee into stroops.
 */
const formatFee = (fee: number): string => `${fee.toLocaleString()} stroops`;

/**
 * Generates a structured markdown report for a given fuzzing run.
 */
export function generateMarkdownReport(run: FuzzingRun): string {
    const timestamp = new Date().toISOString();
    
    let markdown = `# 🚀 Fuzzing Run Report: ${run.id}\n\n`;
    markdown += `Generated on: ${timestamp}\n\n`;

    markdown += `## 📊 Summary\n`;
    markdown += `- **Status:** \`${run.status.toUpperCase()}\`\n`;
    markdown += `- **Area:** ${run.area}\n`;
    markdown += `- **Severity:** ${run.severity.toUpperCase()}\n`;
    markdown += `- **Duration:** ${(run.duration / 1000).toFixed(2)}s\n`;
    markdown += `- **Seeds Explored:** ${run.seedCount.toLocaleString()}\n\n`;

    markdown += `## ⚡ Resource Usage\n`;
    markdown += `- **CPU Instructions:** ${run.cpuInstructions.toLocaleString()}\n`;
    markdown += `- **Memory:** ${formatBytes(run.memoryBytes)}\n`;
    markdown += `- **Min Resource Fee:** ${formatFee(run.minResourceFee)}\n\n`;

    if (run.crashDetail) {
        markdown += `## 💥 Crash Details\n`;
        markdown += `- **Category:** ${run.crashDetail.failureCategory}\n`;
        markdown += `- **Signature:** \`${run.crashDetail.signature}\`\n\n`;

        markdown += `### 📝 Payload\n`;
        markdown += `\`\`\`json\n${run.crashDetail.payload}\n\`\`\`\n\n`;

        markdown += `### 🔁 Replay Locally\n`;
        markdown += `Use the following command to reproduce the crash:\n\n`;
        markdown += `\`\`\`bash\n${run.crashDetail.replayAction}\n\`\`\`\n`;
    } else {
        markdown += `## ✅ No Crashes Detected\n`;
        markdown += `The run completed without identifying any vulnerabilities or panics.\n`;
    }

    markdown += `\n---\n*Report generated by [Soroban CrashLab](https://github.com/SorobanCrashLab/soroban-crashlab)*\n`;

    return markdown;
}
