/**
 * Golden tests for the multi-language reproduction snippet emitters (#1666).
 *
 * - byte-stability: identical fixture bundles must produce byte-identical
 *   output in every language (these strings are the "goldens")
 * - invalid bundles: buildReproducerModel surfaces clean, descriptive errors
 *
 * Compiled and executed via `npm run test` using the tsc + node harness,
 * matching generate-ts-reproducer.test.ts.
 */

import * as assert from 'node:assert/strict';
import { buildReproducerModel, type CaseBundleExport } from './reproducer-model';
import { generateTSReproducerFromBundle } from './generate-ts-reproducer';
import { generateRustReproducer } from './generate-rust-reproducer';
import { generatePythonReproducer } from './generate-python-reproducer';

// ── Fixtures ─────────────────────────────────────────────────────────────────

const FIXTURE_BUNDLE: CaseBundleExport = {
  seedId: 42,
  inputPayloadHex: 'deadbeef',
  failureClass: 'runtime-failure',
  signatureHash: '0xabcd1234',
  mode: 'invoker',
};

const FIXTURE_BUNDLE_WITH_METADATA: CaseBundleExport = {
  seedId: 7,
  inputPayloadHex: 'cafebabe',
  failureClass: 'empty-input',
  signatureHash: '0x0001',
  mode: 'contract',
  envFingerprint: {
    sorobanRpcUrl: 'https://soroban-futurenet.stellar.org',
    networkPassphrase: 'Test SDF Future Network ; October 2022',
    contractId: 'CAS3ODD6H6T4MWOTPGE4ZZGXWJZL4RBRVXHZCWXG7GJNUWQNIVPLJOTJ',
  },
  invokeArgs: [{ name: 'amount', value: '0x01' }],
};

// ── Golden outputs (byte-stable snapshots) ───────────────────────────────────

const GOLDEN_TS = `// Reproducer for: seed-42-runtime-failure
// Dependencies: none
describe('seed-42-runtime-failure', () => {
  it('should reproduce the failure', () => {
    const input = {
      "seedId": 42,
      "payloadHex": "deadbeef",
      "mode": "invoker"
    };
    // Replace with actual function call
    const result = /* call function with input */ undefined;
    // Expected: {"failureClass":"runtime-failure","signatureHash":"0xabcd1234"}
    // Actual:   {"failureClass":"unknown","signatureHash":"0x0000000000000000"}
    expect(result).toEqual({
      "failureClass": "runtime-failure",
      "signatureHash": "0xabcd1234"
    });
  });
});
`;

const GOLDEN_RUST = `// Reproduction snippet for seed 42 (runtime-failure)
// Generated by the shared reproduction-snippet model. Use this in a contract
// integration test (soroban-sdk). It replays the recorded payload bytes and
// expects the same failure class the bundle captured.
use soroban_sdk::{symbol_short, Env, Symbol, Vec};

#[test]
fn reproduce_seed_42_runtime_failure() {
    let env = Env::default();

    // Recorded seed payload (hex): deadbeef
    let payload: Vec<u8> = vec![0xde, 0xad, 0xbe, 0xef];
    // No invoke arguments were recorded with this bundle.
    let invoke: Vec<(Symbol, Vec<u8>)> = Vec::new(&env);

    // Expected failure class: runtime-failure
    // Signature hash:         0xabcd1234
    // Execution mode:         invoker

    // TODO: drive the real contract invocation with \`payload\` and \`invoke\`.
    // Until then, this test reproduces by construction: it fails loudly when
    // the expected failure class is not recorded in the environment.
    assert!(
        !payload.is_empty(),
        "seed payload for {} must not be empty",
        "runtime-failure"
    );
}
`;

const GOLDEN_PYTHON = `#!/usr/bin/env python3
"""Reproduction snippet for seed 42 (runtime-failure).

Generated by the shared reproduction-snippet model. Replays the recorded seed
payload through the Soroban RPC and expects the captured failure class.
"""

import sys
from stellar_sdk import SorobanRpc, Contract, xdr

RPC_URL = "https://soroban-testnet.stellar.org"
NETWORK_PASSPHRASE = "Test SDF Network ; September 2015"
CONTRACT_ID = "YOUR_CONTRACT_ID"
SEED_PAYLOAD_HEX = "deadbeef"
EXPECTED_FAILURE_CLASS = "runtime-failure"
SIGNATURE_HASH = "0xabcd1234"
MODE = "invoker"

INVOKE_ARGS: dict[str, str] = {}  # No invoke arguments were recorded with this bundle.


def main() -> int:
    server = SorobanRpc(RPC_URL, NETWORK_PASSPHRASE)
    contract = Contract(CONTRACT_ID)
    payload = bytes.fromhex(SEED_PAYLOAD_HEX)

    # TODO: drive the real contract call with \`payload\` and \`INVOKE_ARGS\`.
    # Until then, this reproducer fails loudly when the expected failure
    # class is not observed, matching the TypeScript/Rust emitters.
    observed = "unknown"
    if observed != EXPECTED_FAILURE_CLASS:
        print(
            f"reproduction mismatch: expected {EXPECTED_FAILURE_CLASS}, "
            f"observed {observed}",
            file=sys.stderr,
        )
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
`;

// ── Byte-stability tests ─────────────────────────────────────────────────────

function testTypeScriptGoldenByteStable(): void {
  const model = buildReproducerModel(FIXTURE_BUNDLE);
  assert.equal(
    generateTSReproducerFromBundle(FIXTURE_BUNDLE),
    GOLDEN_TS,
    'TypeScript emitter golden must not change (byte-stable)',
  );
  assert.equal(
    generateTSReproducerFromBundle(FIXTURE_BUNDLE),
    generateTSReproducerFromBundle(FIXTURE_BUNDLE),
    'TypeScript emitter must be deterministic',
  );
  assert.ok(
    generateTSReproducerFromBundle(FIXTURE_BUNDLE).includes(String(model.seedId)),
    'model seedId should appear in TS output',
  );
  console.log('✓ testTypeScriptGoldenByteStable');
}

function testRustGoldenByteStable(): void {
  const model = buildReproducerModel(FIXTURE_BUNDLE);
  const snippet = generateRustReproducer(model);
  assert.equal(snippet, GOLDEN_RUST, 'Rust emitter golden must not change (byte-stable)');
  assert.equal(generateRustReproducer(model), generateRustReproducer(model), 'Rust emitter must be deterministic');
  console.log('✓ testRustGoldenByteStable');
}

function testPythonGoldenByteStable(): void {
  const model = buildReproducerModel(FIXTURE_BUNDLE);
  const snippet = generatePythonReproducer(model);
  assert.equal(snippet, GOLDEN_PYTHON, 'Python emitter golden must not change (byte-stable)');
  assert.equal(
    generatePythonReproducer(model),
    generatePythonReproducer(model),
    'Python emitter must be deterministic',
  );
  console.log('✓ testPythonGoldenByteStable');
}

function testMetadataBundleEmittersDeterministic(): void {
  const model = buildReproducerModel(FIXTURE_BUNDLE_WITH_METADATA);
  const rust = generateRustReproducer(model);
  const python = generatePythonReproducer(model);
  assert.ok(rust.includes('CAS3ODD6H6T4MWOTPGE4ZZGXWJZL4RBRVXHZCWXG7GJNUWQNIVPLJOTJ'), 'Rust should embed contract id');
  assert.ok(rust.includes('vec![0xca, 0xfe, 0xba, 0xbe]'), 'Rust should embed payload bytes');
  const rpcUrlLine = python.split('\n').find((line) => line.startsWith('RPC_URL = '));
  assert.strictEqual(
    rpcUrlLine,
    `RPC_URL = "${model.envFingerprint?.sorobanRpcUrl}"`,
    'Python should embed RPC url',
  );
  assert.ok(python.includes('0x01'), 'Python should embed invoke arg value');
  assert.equal(rust, generateRustReproducer(model), 'Rust emitter must be deterministic');
  assert.equal(python, generatePythonReproducer(model), 'Python emitter must be deterministic');
  console.log('✓ testMetadataBundleEmittersDeterministic');
}

// ── Invalid bundle tests ─────────────────────────────────────────────────────

function assertBundleError(bundle: unknown, messagePart: string, label: string): void {
  assert.throws(
    () => buildReproducerModel(bundle as CaseBundleExport),
    (err: unknown) => err instanceof Error && err.message.includes(messagePart),
    `${label} should throw a clean error mentioning "${messagePart}"`,
  );
  console.log(`✓ ${label}`);
}

function testInvalidBundlesThrowCleanErrors(): void {
  assertBundleError(null, 'expected an object', 'null bundle');
  assertBundleError({} as CaseBundleExport, 'seedId', 'missing seedId');
  assertBundleError(
    { seedId: 42, inputPayloadHex: 'zzzz', failureClass: 'x', signatureHash: '0x00', mode: 'invoker' } as CaseBundleExport,
    'inputPayloadHex',
    'non-hex payload',
  );
  assertBundleError(
    { seedId: 42, inputPayloadHex: 'deadbeef', failureClass: 'x', signatureHash: 'abc', mode: 'invoker' } as CaseBundleExport,
    'signatureHash',
    'odd-length signature hash',
  );
  assertBundleError(
    { seedId: -1, inputPayloadHex: 'deadbeef', failureClass: 'x', signatureHash: '0x00', mode: 'invoker' } as CaseBundleExport,
    'seedId',
    'negative seedId',
  );
  assertBundleError(
    { seedId: 42, inputPayloadHex: 'deadbeef', failureClass: 'x', signatureHash: '0x00', mode: 'invoker', invokeArgs: 'nope' } as unknown as CaseBundleExport,
    'invokeArgs',
    'non-array invokeArgs',
  );
}

// ── Runner ───────────────────────────────────────────────────────────────────

testTypeScriptGoldenByteStable();
testRustGoldenByteStable();
testPythonGoldenByteStable();
testMetadataBundleEmittersDeterministic();
testInvalidBundlesThrowCleanErrors();

console.log('All reproducer-emitters tests passed.');