export function buildGitHubIssueUrl(cluster: { signature: string; count: number; area: string }, runs: { id: string }[]): string {
  const title = encodeURIComponent(`Crash: ${cluster.signature} (${cluster.area}) — ${cluster.count} occurrences`);
  const body = encodeURIComponent(`## Failure Cluster\n\n**Signature:** \`${cluster.signature}\`\n**Area:** ${cluster.area}\n**Occurrences:** ${cluster.count}\n\n**Affected runs:**\n${runs.map((r) => `- ${r.id}`).join('\n')}\n\n*Generated by Soroban CrashLab*`);
  return `https://github.com/SorobanCrashLab/soroban-crashlab/issues/new?title=${title}&body=${body}`;
}
